### ISSUE TITLE
Gitflow - Branch naming

### ISSUE THREAD

**Issue by olivierobert** [longnd/google-scraper#14]
First Kudos for using PRs and merging code bit by bit as it gives us a good insight on your process.

Regarding branching, we noticed that you did not follow the standard git flow: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow. This can be broken into two main ideas:

- Having 2 main branches: `master` and `develop`
- naming branches based on types: `feature/xxxx`, `chore/xxxx` and `bug/xxxx`

So if I take as an example some of your branches, here is what it should be:
- `optimize-js-code` -> `chore/optimize-js-code`
- `create-the-scraper` -> `feature/create-the-scraper`

Github flow - which is currently used - is rather too simple in most cases.

**Comment by longnd** [comment]
I do understand [git-flow by Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model) which is something becoming a common practice nowadays - we - at my current company - also applying it to our development process. But I disagree that it should be a standard but one of the good practices. It depends on a team and their the development process to chose a workflow suits best for them.
There has been some controversy over the usage of that git-flow [(1)](https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/) [(2)](https://hackernoon.com/gitflow-is-a-poor-branching-model-hack-d46567a156e7) that we should consider.

I also found out [Github flow](https://guides.github.com/introduction/flow/) introducted through a comprehenside [article](http://scottchacon.com/2011/08/31/github-flow.html) quite interesting, that's why I wanted to give it a try in this code challenge

**Comment by olivierobert** [comment]
@longnd I agree with you that each workflow needs to suit each team :-)

But I believe, at least separating the branches by types `feature/`, `chore` and `bug` has many organizational advantages when working in teams. The debate of having a branch `master` only or two branches like `master` + `develop` is as old as the debate about squashing commits 😅

In any case, I understand your reasoning here and that works fine here

**Comment by longnd** [comment]
Yes, I agree that separating the branches by types (`feature/` for example) is a descriptive naming pattern and it gives everyone else a clearer understanding of what the branch is about and I'll pay attention to that.
I'm going to close this issue as we're all clear.
